# Generated by Django 2.2.6 on 2020-01-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('nivel_academico', models.CharField(blank=True, choices=[('k', 'Kinder'), ('p', 'Primaria'), ('s', 'Secundaria'), ('b', 'bachillerato'), ('u', 'universidad')], help_text='Elige el nivel académico del alumno', max_length=1)),
                ('date_joined', models.DateTimeField(auto_now=True, verbose_name='fecha de inicio')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Ultima fecha de Sesión')),
                ('is_admin', models.BooleanField(default=False, verbose_name='¿Es Administrador?')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Esta Acivo?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='¿Es parte del Staff?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='¿Es Super Usuario?')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
