# Generated by Django 2.2.9 on 2020-05-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Grupo al que pertenece el usuario', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
    ]
