# Generated by Django 2.2.6 on 2020-01-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20200117_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, max_length=8, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
