# Generated by Django 2.2.9 on 2020-02-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20200218_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
