# Generated by Django 2.2.9 on 2020-05-20 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20200513_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='grupo',
        ),
    ]
