# Generated by Django 2.2.9 on 2020-02-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_usuario_facebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
