# Generated by Django 2.2.6 on 2020-01-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_auto_20200117_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='numero',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de contacto'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nivel_academico',
            field=models.CharField(blank=True, choices=[('k', 'Kinder'), ('p', 'Primaria'), ('s', 'Secundaria'), ('b', 'bachillerato'), ('u', 'universidad')], max_length=1, verbose_name='Nivel académico del alumno'),
        ),
    ]
