# Generated by Django 2.2.6 on 2020-01-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_auto_20200117_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='asistencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Días de asistencia'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='edad_madre',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='edad_padre',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='enfoque',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Area en la que guste que se enfocará la atención'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre_madre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la Madre'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre_padre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Padre'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ocupacion_madre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocupación'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ocupacion_padre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocupación'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='padecimientos',
            field=models.TextField(blank=True, null=True, verbose_name='Alergias o padecimientos'),
        ),
    ]
