# Generated by Django 2.2.9 on 2020-06-10 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_auto_20200521_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='grupo',
        ),
    ]
