# Generated by Django 2.2.6 on 2020-01-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_auto_20200119_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='numero',
            new_name='numero_madre',
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_padre',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de contacto'),
        ),
    ]
