# Generated by Django 2.2.6 on 2020-01-23 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_auto_20200119_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='edad_madre',
            new_name='edad_de_la_madre',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='edad_padre',
            new_name='edad_del_padre',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre_madre',
            new_name='nombre_de_la_madre',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre_padre',
            new_name='nombre_del_padre',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='numero_madre',
            new_name='numero_de_la_madre',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='numero_padre',
            new_name='numero_del_padre',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='ocupacion_madre',
            new_name='ocupacion_de_la_madre',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='ocupacion_padre',
            new_name='ocupacion_del_padre',
        ),
    ]
