# Generated by Django 2.2.6 on 2020-01-26 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_auto_20200123_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUsuario',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('imagen', models.TextField(default='default.jpg', max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=60)),
                ('username', models.CharField(db_index=True, max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('padecimientos', models.TextField(blank=True, null=True, verbose_name='Alergias o padecimientos')),
                ('asistencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Días de asistencia')),
                ('enfoque', models.CharField(blank=True, max_length=100, null=True, verbose_name='Area en la que guste que se enfocará la atención')),
                ('nombre_de_la_madre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la Madre')),
                ('edad_de_la_madre', models.IntegerField(blank=True, null=True, verbose_name='Edad')),
                ('ocupacion_de_la_madre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocupación')),
                ('numero_de_la_madre', models.IntegerField(blank=True, null=True, verbose_name='Número de contacto')),
                ('nombre_del_padre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Padre')),
                ('edad_del_padre', models.IntegerField(blank=True, null=True, verbose_name='Edad')),
                ('ocupacion_del_padre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocupación')),
                ('numero_del_padre', models.IntegerField(blank=True, null=True, verbose_name='Número de contacto')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('escuela', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nombre de la escuela')),
                ('domicilio', models.CharField(blank=True, max_length=150, null=True, verbose_name='Domicilio')),
                ('nivel_academico', models.CharField(blank=True, choices=[('k', 'Kinder'), ('p', 'Primaria'), ('s', 'Secundaria'), ('b', 'bachillerato'), ('u', 'universidad')], max_length=1, verbose_name='Nivel académico del alumno')),
                ('date_joined', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de ingreso')),
                ('last_login', models.DateTimeField(blank=True, editable=False, verbose_name='Ultima fecha de Sesión')),
                ('is_admin', models.BooleanField(default=False, verbose_name='¿Es Administrador?')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Esta Acivo?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='¿Es parte del Staff?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='¿Es Super Usuario?')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical usuario',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
