# Generated by Django 2.2.6 on 2020-01-26 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_historicalusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalUsuario',
        ),
    ]
