# Generated by Django 2.2.6 on 2020-01-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_delete_historicalusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='status_paquetes',
            field=models.BooleanField(default=False, verbose_name='Tiene Paquetes Activos?'),
        ),
    ]
