# Generated by Django 2.2.6 on 2020-01-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_usuario_status_paquetes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='status_paquetes',
            field=models.BooleanField(default=False, verbose_name='¿Tiene Paquetes Activos?'),
        ),
    ]
