# Generated by Django 2.2.6 on 2020-01-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0014_auto_20200129_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='padecimientos',
            field=models.TextField(blank=True, null=True, verbose_name='padecimientos'),
        ),
    ]
