# Generated by Django 2.2.6 on 2020-01-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0016_auto_20200130_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='user_login@hotmail.com', help_text='Si no cuentas con un email el valor por dafault', max_length=60, unique=True),
        ),
    ]
