# Generated by Django 2.2.6 on 2020-01-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0018_auto_20200130_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=60, unique=True),
        ),
    ]
