# Generated by Django 2.2.9 on 2020-02-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0021_auto_20200203_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
