# Generated by Django 2.2.9 on 2020-02-16 05:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='id del comentario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('mensaje', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='id del mensaje', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('asunto', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='id del Post', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
                ('imagen', models.ImageField(blank=True, upload_to='post_image/%Y/%m/%d')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('content', models.TextField()),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'borrador'), (1, 'publicado')], default=0)),
            ],
            options={
                'ordering': ['-create_on'],
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='default.jpg', upload_to='profesores_pics')),
                ('nombre', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Profesores',
            },
        ),
        migrations.CreateModel(
            name='Rotulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcabecera', models.CharField(default='Bienvenido al Club de Tareas', max_length=100)),
                ('cabecera', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(upload_to='rotulos_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='default.jpg', upload_to='testimonios_pics')),
                ('nombre', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('profesion', models.CharField(max_length=100)),
            ],
        ),
    ]
