# Generated by Django 2.2.6 on 2020-01-12 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='id del mensaje', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('asunto', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='id del Post', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
                ('imagen', models.ImageField(blank=True, upload_to='post_image/%Y/%m/%d')),
                ('video', embed_video.fields.EmbedVideoField(blank=True)),
                ('content', models.TextField()),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'borrador'), (1, 'publicado')], default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_on'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='id del comentario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('mensaje', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='blog.Post')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
