# Generated by Django 2.2.9 on 2020-02-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200215_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='publicidad_pics')),
            ],
            options={
                'verbose_name_plural': 'Carteles de Publicidad',
            },
        ),
    ]
