# Generated by Django 2.2.6 on 2020-01-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200119_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='default.jpg', upload_to='testimonios_pics')),
                ('nombre', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('profesion', models.CharField(max_length=100)),
            ],
        ),
    ]
