# Generated by Django 2.2.9 on 2020-02-25 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_publicidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['created_on'], 'verbose_name_plural': 'Comentarios de Posts'},
        ),
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ['created_on'], 'verbose_name_plural': 'Mensajes(Formulario de Contacto)'},
        ),
    ]
