# Generated by Django 2.2.6 on 2020-01-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_testimonio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcabecera', models.CharField(default='Bienvenido al Club de Tareas', max_length=100)),
                ('cabecera', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(upload_to='rotulos_pics')),
            ],
        ),
    ]
