# Generated by Django 2.2.9 on 2020-02-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200225_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='test_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
