# Generated by Django 2.2.9 on 2020-02-26 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_mensaje_test_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='test_number',
        ),
    ]
