# Generated by Django 2.2.6 on 2020-01-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='imagen',
            field=models.ImageField(default='default.jpg', upload_to='profesores_pics'),
        ),
    ]
