# Generated by Django 2.2.9 on 2020-02-28 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_mensaje_test_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='blog.Post'),
        ),
    ]
