# Generated by Django 2.2.9 on 2020-03-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_servicio_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='icono',
            field=models.CharField(blank=True, choices=[('commenting', 'Comentario'), ('book', 'Libro'), ('th', 'Cuadricula'), ('file-text', 'Archivo'), ('cogs', 'Engranes'), ('spinner', 'Spinner'), ('slack', 'slack')], max_length=20),
        ),
    ]
