# Generated by Django 2.2.9 on 2020-03-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200309_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='icono',
            field=models.CharField(blank=True, choices=[('commenting', 'Comentario'), ('book', 'Libro'), ('th', 'Cuadricula'), ('file-text', 'Archivo'), ('cogs', 'Engranes'), ('spinner', 'Spinner'), ('gg', 'gg'), ('sort-alpha-desc', 'sort-alpha-desc'), ('sort-numeric-asc', 'sort-numeric-asc'), ('snowflake-o', 'snowflake-o'), ('share-alt', 'share-alt')], max_length=20),
        ),
    ]
