# Generated by Django 2.2.6 on 2020-01-19 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200118_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete_inscrito',
            name='horas_consumidas',
            field=models.TimeField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='paquete_inscrito',
            name='horas_restantes',
            field=models.TimeField(default=datetime.timedelta(0)),
        ),
    ]
