# Generated by Django 2.2.9 on 2020-05-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200512_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='asunto',
            field=models.CharField(default='Mensaje de Usuario', max_length=100),
        ),
    ]
