# Generated by Django 2.2.6 on 2020-01-19 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200119_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete_inscrito',
            name='horas_consumidas',
            field=models.TimeField(default=datetime.datetime(2020, 1, 19, 0, 0, 0, 811337)),
        ),
        migrations.AlterField(
            model_name='paquete_inscrito',
            name='horas_restantes',
            field=models.TimeField(default=datetime.datetime(2020, 1, 19, 0, 0, 0, 811385)),
        ),
    ]
