# Generated by Django 2.2.9 on 2020-02-17 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_evento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
