# Generated by Django 2.2.6 on 2020-01-19 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200119_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete_inscrito',
            name='horas_consumidas',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='paquete_inscrito',
            name='horas_restantes',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
