# Generated by Django 2.2.9 on 2020-02-17 21:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='id de la sesion', primary_key=True, serialize=False),
        ),
    ]
