# Generated by Django 2.2.9 on 2020-02-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200217_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='titulo',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='asunto',
            field=models.CharField(default='Notifiación del Staff', max_length=100),
        ),
    ]
