# Generated by Django 2.2.6 on 2020-01-20 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200119_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paquete_inscrito',
            old_name='horas_restantes',
            new_name='tiempo_restante',
        ),
    ]
