# Generated by Django 2.2.6 on 2020-01-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200119_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete_inscrito',
            name='horas_restantes',
            field=models.CharField(default='00:00:00', max_length=100),
        ),
    ]
