# Generated by Django 2.2.6 on 2020-01-20 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_paquete_inscrito_horas_restantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete_inscrito',
            name='tiempo_consumido',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='paquete_inscrito',
            name='horas_consumidas',
            field=models.CharField(default='00:00:00', max_length=100),
        ),
    ]
