# Generated by Django 2.2.6 on 2020-01-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200119_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcabecera', models.CharField(default='Bienvenido al Club de Tareas', max_length=100)),
                ('cabecera', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(upload_to='rotulos_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='default.jpg', upload_to='testimonios_pics')),
                ('nombre', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('profesion', models.CharField(max_length=100)),
            ],
        ),
    ]
