# Generated by Django 2.2.6 on 2020-01-21 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rotulo_testimonio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonio',
        ),
    ]
