# Generated by Django 2.2.6 on 2020-01-22 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_delete_testimonio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rotulo',
        ),
    ]
