# Generated by Django 2.2.6 on 2020-01-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_eventuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventuser',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
