# Generated by Django 2.2.6 on 2020-01-28 05:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0018_eventuser_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifiacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True)),
                ('observadores', models.ManyToManyField(blank=True, null=True, related_name='observadores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notificaciones',
            },
        ),
    ]
