# Generated by Django 2.2.6 on 2020-01-28 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_notifiacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifiacion',
            name='observadores',
        ),
    ]
