# Generated by Django 2.2.6 on 2020-01-28 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0020_remove_notifiacion_observadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifiacion',
            name='usuarios',
            field=models.ManyToManyField(null=True, related_name='notificacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
