# Generated by Django 2.2.6 on 2020-01-28 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_notifiacion_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifiacion',
            name='usuarios',
        ),
    ]
