# Generated by Django 2.2.6 on 2020-01-31 20:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0022_remove_notifiacion_usuarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventUser',
            new_name='Historial_User',
        ),
    ]
