# Generated by Django 2.2.6 on 2020-02-02 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0023_auto_20200131_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifiacion',
            name='author',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'students'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
