# Generated by Django 2.2.6 on 2020-02-02 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_notifiacion_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifiacion',
            name='author',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'estudiantes'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
