# Generated by Django 2.2.6 on 2020-02-02 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('app', '0025_auto_20200202_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifiacion',
            name='author',
        ),
        migrations.AddField(
            model_name='notifiacion',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
