# Generated by Django 2.2.6 on 2020-02-02 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('app', '0026_auto_20200202_1153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifiacion',
            new_name='Notificacion',
        ),
    ]
