# Generated by Django 2.2.6 on 2020-02-02 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20200202_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'verbose_name_plural': 'Envio de Notificaciones a grupos'},
        ),
    ]
